# frozen_string_literal: true

class InvoiceBillingProfile < ApplicationRecord
  belongs_to :organization
  has_many :invoices, dependent: :restrict_with_error

  before_validation :normalize_blanks
  before_save :clear_other_defaults, if: :is_default?

  validates :name, presence: true, uniqueness: { scope: :organization_id }
  validates :invoice_prefix, length: { maximum: 16 }, allow_blank: true

  scope :active, -> { where(active: true) }
  scope :ordered, -> { order(Arel.sql("is_default DESC"), :name, :id) }

  def self.ensure_default_for!(organization)
    organization.with_lock do
      existing = organization.invoice_billing_profiles.active.order(Arel.sql("is_default DESC"), :id).first
      return existing if existing

      primary_company = organization.primary_company || organization.companies.order(:id).first
      organization.invoice_billing_profiles.create!(
        name: organization.name,
        legal_name: organization.name,
        phone: primary_company&.phone,
        email: primary_company&.email,
        address: company_address(primary_company),
        invoice_prefix: "INV",
        remit_to: organization.name,
        footer_note: "Generated by Cornerstone Payroll.",
        is_default: true
      )
    end
  end

  def self.company_address(company)
    return nil unless company

    [
      company.address_line1,
      company.address_line2,
      [ company.city, company.state, company.zip ].compact_blank.join(", ").presence
    ].compact_blank.join("\n").presence
  end

  private

  def normalize_blanks
    self.name = name.to_s.strip
    self.legal_name = legal_name.to_s.strip.presence
    self.website = website.to_s.strip.presence
    self.phone = phone.to_s.strip.presence
    self.email = email.to_s.strip.presence
    self.address = address.to_s.strip.presence
    self.payment_instructions = payment_instructions.to_s.strip.presence
    self.default_payment_terms = default_payment_terms.to_s.strip.presence
    self.invoice_prefix = invoice_prefix.to_s.strip.presence
    self.remit_to = remit_to.to_s.strip.presence
    self.footer_note = footer_note.to_s.strip.presence
    self.active = true if active.nil?
  end

  def clear_other_defaults
    self.class.where(organization_id: organization_id, is_default: true)
      .where.not(id: id)
      .update_all(is_default: false)
  end
end
