# frozen_string_literal: true

class InvoiceBillingProfile < ApplicationRecord
  LEGACY_DEFAULT_FOOTER = "Generated by Cornerstone Payroll."
  DEFAULT_FOOTER = "Thank you for your business."
  belongs_to :organization
  has_many :invoices, dependent: :restrict_with_error
  has_many :invoice_number_sequences, dependent: :restrict_with_error

  before_validation :normalize_blanks
  before_save :clear_other_defaults, if: :is_default?

  validates :name, presence: true, uniqueness: { scope: :organization_id }
  validates :invoice_prefix, length: { maximum: 16 }, allow_blank: true

  scope :active, -> { where(active: true) }
  scope :ordered, -> { order(Arel.sql("is_default DESC"), :name, :id) }

  def self.ensure_default_for!(organization)
    organization.with_lock do
      profiles = organization.invoice_billing_profiles
      profiles.where(active: false, is_default: true).update_all(is_default: false)

      existing_default = profiles.active.where(is_default: true).order(:id).first
      if existing_default
        existing_default.update!(footer_note: DEFAULT_FOOTER) if existing_default.footer_note == LEGACY_DEFAULT_FOOTER
        return existing_default
      end

      existing_active = profiles.active.order(:id).first
      if existing_active
        existing_active.update!(is_default: true, footer_note: refreshed_footer(existing_active.footer_note))
        return existing_active
      end

      primary_company = organization.primary_company || organization.companies.order(:id).first
      profile = profiles.find_or_initialize_by(name: organization.name)
      profile.update!(
        legal_name: profile.legal_name.presence || organization.name,
        phone: profile.phone.presence || primary_company&.phone,
        email: profile.email.presence || primary_company&.email,
        address: profile.address.presence || company_address(primary_company),
        invoice_prefix: profile.invoice_prefix.presence || "INV",
        remit_to: profile.remit_to.presence || organization.name,
        footer_note: refreshed_footer(profile.footer_note),
        active: true,
        is_default: true
      )
      profile
    end
  end

  def self.company_address(company)
    return nil unless company

    [
      company.address_line1,
      company.address_line2,
      [ company.city, company.state, company.zip ].compact_blank.join(", ").presence
    ].compact_blank.join("\n").presence
  end

  def self.refreshed_footer(value)
    value.blank? || value == LEGACY_DEFAULT_FOOTER ? DEFAULT_FOOTER : value
  end

  private

  def normalize_blanks
    self.name = name.to_s.strip
    self.legal_name = legal_name.to_s.strip.presence
    self.website = website.to_s.strip.presence
    self.phone = phone.to_s.strip.presence
    self.email = email.to_s.strip.presence
    self.address = address.to_s.strip.presence
    self.payment_instructions = payment_instructions.to_s.strip.presence
    self.default_payment_terms = default_payment_terms.to_s.strip.presence
    self.invoice_prefix = invoice_prefix.to_s.strip.presence
    self.remit_to = remit_to.to_s.strip.presence
    self.footer_note = footer_note.to_s.strip.presence
    self.active = true if active.nil?
    self.is_default = false unless active?
  end

  def clear_other_defaults
    self.class.where(organization_id: organization_id, is_default: true)
      .where.not(id: id)
      .update_all(is_default: false)
  end
end
