# frozen_string_literal: true

class AddInvoiceBillingProfilesAndSnapshots < ActiveRecord::Migration[8.1]
  def up
    create_table :invoice_billing_profiles do |t|
      t.references :organization, null: false, foreign_key: true
      t.string :name, null: false
      t.string :legal_name
      t.string :website
      t.string :phone
      t.string :email
      t.text :address
      t.text :payment_instructions
      t.text :default_payment_terms
      t.string :invoice_prefix
      t.string :remit_to
      t.text :footer_note
      t.boolean :active, default: true, null: false
      t.boolean :is_default, default: false, null: false
      t.timestamps
    end

    add_index :invoice_billing_profiles, [ :organization_id, :name ], unique: true
    add_index :invoice_billing_profiles, [ :organization_id, :is_default ],
      unique: true,
      where: "is_default = true",
      name: "index_invoice_billing_profiles_one_default_per_org"

    add_reference :invoice_recipients, :organization, foreign_key: true
    add_reference :invoices, :organization, foreign_key: true
    add_reference :invoices, :invoice_billing_profile, foreign_key: true
    add_column :invoices, :snapshot, :jsonb, default: {}, null: false
    add_column :invoices, :snapshot_version, :integer, default: 1, null: false

    execute <<~SQL.squish
      UPDATE invoice_recipients
      SET organization_id = companies.organization_id
      FROM companies
      WHERE invoice_recipients.company_id = companies.id
    SQL

    execute <<~SQL.squish
      UPDATE invoices
      SET organization_id = companies.organization_id
      FROM companies
      WHERE invoices.company_id = companies.id
    SQL

    execute <<~SQL.squish
      INSERT INTO invoice_billing_profiles (
        organization_id,
        name,
        legal_name,
        website,
        phone,
        email,
        address,
        payment_instructions,
        default_payment_terms,
        invoice_prefix,
        remit_to,
        footer_note,
        active,
        is_default,
        created_at,
        updated_at
      )
      SELECT
        organizations.id,
        organizations.name,
        organizations.name,
        NULL,
        companies.phone,
        companies.email,
        concat_ws(E'\n',
          companies.address_line1,
          companies.address_line2,
          NULLIF(concat_ws(', ', companies.city, concat_ws(' ', companies.state, companies.zip)), '')
        ),
        'Please remit payment according to the instructions on this invoice.',
        'Due on receipt',
        'INV',
        organizations.name,
        'Generated by Cornerstone Payroll.',
        TRUE,
        TRUE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
      FROM organizations
      LEFT JOIN companies ON companies.id = organizations.primary_company_id
      WHERE NOT EXISTS (
        SELECT 1 FROM invoice_billing_profiles existing
        WHERE existing.organization_id = organizations.id
      )
    SQL

    execute <<~SQL.squish
      INSERT INTO invoice_billing_profiles (
        organization_id,
        name,
        legal_name,
        website,
        phone,
        email,
        address,
        payment_instructions,
        default_payment_terms,
        invoice_prefix,
        remit_to,
        footer_note,
        active,
        is_default,
        created_at,
        updated_at
      )
      SELECT
        organizations.id,
        'Shimizu Technology',
        'Shimizu Technology',
        'https://shimizu-technology.com',
        '671-483-0219',
        NULL,
        NULL,
        'Please remit payment according to the instructions on this invoice.',
        'Due on receipt',
        'ST',
        'Shimizu Technology',
        'Generated by Cornerstone Payroll.',
        TRUE,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
      FROM organizations
      WHERE organizations.name ILIKE '%cornerstone%'
        AND NOT EXISTS (
          SELECT 1 FROM invoice_billing_profiles existing
          WHERE existing.organization_id = organizations.id
            AND existing.name = 'Shimizu Technology'
        )
    SQL

    execute <<~SQL.squish
      UPDATE invoices
      SET invoice_billing_profile_id = invoice_billing_profiles.id
      FROM invoice_billing_profiles
      WHERE invoices.organization_id = invoice_billing_profiles.organization_id
        AND invoice_billing_profiles.is_default = TRUE
    SQL

    change_column_null :invoice_recipients, :organization_id, false
    change_column_null :invoices, :organization_id, false
    change_column_null :invoices, :invoice_billing_profile_id, false

    remove_index :invoices, name: "index_invoices_on_company_id_and_invoice_number"

    execute <<~SQL.squish
      WITH duplicate_invoices AS (
        SELECT
          id,
          invoice_number,
          ROW_NUMBER() OVER (
            PARTITION BY invoice_billing_profile_id, invoice_number
            ORDER BY id
          ) AS duplicate_position
        FROM invoices
        WHERE invoice_number IS NOT NULL
      )
      UPDATE invoices
      SET invoice_number = duplicate_invoices.invoice_number || '-DUP-' || invoices.id::text
      FROM duplicate_invoices
      WHERE invoices.id = duplicate_invoices.id
        AND duplicate_invoices.duplicate_position > 1
    SQL

    add_index :invoice_recipients, [ :organization_id, :name ], name: "index_invoice_recipients_on_org_name"
    add_index :invoices, [ :organization_id, :invoice_date ], name: "index_invoices_on_org_invoice_date"
    add_index :invoices, [ :organization_id, :status ], name: "index_invoices_on_org_status"
    add_index :invoices, [ :invoice_billing_profile_id, :invoice_number ],
      unique: true,
      name: "index_invoices_on_billing_profile_invoice_number"
  end

  def down
    remove_index :invoices, name: "index_invoices_on_billing_profile_invoice_number"
    add_index :invoices, [ :company_id, :invoice_number ],
      unique: true,
      name: "index_invoices_on_company_id_and_invoice_number"
    remove_index :invoices, name: "index_invoices_on_org_status"
    remove_index :invoices, name: "index_invoices_on_org_invoice_date"
    remove_index :invoice_recipients, name: "index_invoice_recipients_on_org_name"

    remove_column :invoices, :snapshot_version
    remove_column :invoices, :snapshot
    remove_reference :invoices, :invoice_billing_profile, foreign_key: true
    remove_reference :invoices, :organization, foreign_key: true
    remove_reference :invoice_recipients, :organization, foreign_key: true

    drop_table :invoice_billing_profiles
  end
end
