# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: async

test:
  adapter: test

production:
  adapter: <%= ENV.fetch("USE_SOLID_CABLE", "false").to_s.downcase == "true" ? "solid_cable" : "async" %>
  <% if ENV.fetch("USE_SOLID_CABLE", "false").to_s.downcase == "true" %>
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
  <% end %>
