# frozen_string_literal: true

require "prawn"
require "prawn/table"

class InvoicePdfGenerator
  include ActionView::Helpers::NumberHelper

  PAGE_MARGIN = 54

  def initialize(invoice)
    @invoice = invoice
    @company = invoice.company
    @recipient = invoice.invoice_recipient
  end

  def filename
    number = @invoice.invoice_number.to_s.parameterize.presence || "invoice"
    "invoice-#{number}.pdf"
  end

  def generate
    Prawn::Document.new(page_size: "LETTER", margin: PAGE_MARGIN) do |pdf|
      header(pdf)
      parties(pdf)
      invoice_meta(pdf)
      line_items(pdf)
      totals(pdf)
      notes(pdf)
      footer(pdf)
    end.render
  end

  private

  def header(pdf)
    pdf.fill_color "111827"
    pdf.text "INVOICE", size: 28, style: :bold
    pdf.move_down 8
    pdf.fill_color "4B5563"
    pdf.text @company.name.to_s, size: 12, style: :bold
    company_lines.each { |line| pdf.text line, size: 9 }
    pdf.fill_color "000000"
  end

  def parties(pdf)
    pdf.move_down 28
    bill_to = ([ "Bill To", @recipient.name ] + @recipient.address.to_s.split("\n") + [ @recipient.email ]).compact_blank.join("\n")
    from = ([ "From", @company.name ] + company_lines).compact_blank.join("\n")

    pdf.table([[ bill_to, from ]], cell_style: { borders: [], padding: [ 0, 8, 0, 0 ], size: 10 }) do
      columns(0).width = 240
      columns(1).width = 240
    end
  end

  def invoice_meta(pdf)
    pdf.move_down 24
    rows = [
      [ "Invoice #", @invoice.invoice_number ],
      [ "Invoice Date", format_date(@invoice.invoice_date) ],
      [ "Service Period", service_period ],
      [ "Status", @invoice.status.titleize ]
    ].reject { |_label, value| value.blank? }

    pdf.table(rows, width: pdf.bounds.width, cell_style: { size: 10, padding: [ 6, 8 ], border_color: "E5E7EB" }) do
      columns(0).font_style = :bold
      columns(0).text_color = "374151"
      columns(0).width = 130
      columns(1).width = pdf.bounds.width - 130
    end
  end

  def line_items(pdf)
    pdf.move_down 24
    rows = [
      [
        { content: "Description", font_style: :bold },
        { content: "Date", font_style: :bold },
        { content: "Qty", font_style: :bold, align: :right },
        { content: "Rate", font_style: :bold, align: :right },
        { content: "Amount", font_style: :bold, align: :right }
      ]
    ]

    @invoice.line_items.each do |item|
      rows << [
        item.description,
        format_date(item.service_date),
        format_decimal(item.quantity),
        money(item.rate),
        money(item.amount)
      ]
    end

    pdf.table(rows, header: true, width: pdf.bounds.width, cell_style: { size: 9, padding: [ 8, 7 ], border_color: "E5E7EB" }) do
      row(0).background_color = "F3F4F6"
      row(0).text_color = "111827"
      columns(0).width = 230
      columns(1).width = 78
      columns(2).width = 55
      columns(3).width = 80
      columns(4).width = 85
      columns(2..4).align = :right
    end
  end

  def totals(pdf)
    pdf.move_down 12
    pdf.bounding_box([ pdf.bounds.right - 180, pdf.cursor ], width: 180) do
      pdf.table([[ "Total", money(@invoice.total_amount) ]], width: 180, cell_style: { size: 12, padding: [ 8, 8 ], border_color: "D1D5DB" }) do
        columns(0).font_style = :bold
        columns(1).font_style = :bold
        columns(1).align = :right
      end
    end
  end

  def notes(pdf)
    if @invoice.payment_terms.present?
      pdf.move_down 28
      pdf.fill_color "374151"
      pdf.text "Payment Terms", size: 11, style: :bold
      pdf.fill_color "111827"
      pdf.text @invoice.payment_terms, size: 10
    end

    return if @invoice.notes.blank?

    pdf.move_down 16
    pdf.fill_color "374151"
    pdf.text "Notes", size: 11, style: :bold
    pdf.fill_color "111827"
    pdf.text @invoice.notes, size: 10
  end

  def footer(pdf)
    pdf.repeat(:all) do
      pdf.bounding_box([ pdf.bounds.left, 24 ], width: pdf.bounds.width, height: 20) do
        pdf.fill_color "9CA3AF"
        pdf.text "Generated by Cornerstone Payroll", size: 8, align: :center
        pdf.fill_color "000000"
      end
    end
  end

  def company_lines
    [
      @company.address_line1,
      @company.address_line2,
      [ @company.city, @company.state, @company.zip ].compact_blank.join(", ").presence,
      @company.email,
      @company.phone
    ].compact_blank
  end

  def service_period
    return nil if @invoice.service_period_start.blank? && @invoice.service_period_end.blank?

    [ format_date(@invoice.service_period_start), format_date(@invoice.service_period_end) ].compact_blank.join(" - ")
  end

  def format_date(value)
    value&.strftime("%m/%d/%Y")
  end

  def format_decimal(value)
    number_with_precision(value || 0, precision: 2, delimiter: ",")
  end

  def money(value)
    number_to_currency(value || 0)
  end
end
